config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'bootstrap/index'
  resources :comments
  devise_for :users
  devise_for :admins
  resources :courses do
      member do
      put "like", to: "courses#upvote"
      put "dislike", to: "courses#downvote"
    end
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :courses
  has_one_attached :avatar
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :admin 
    acts_as_votable
    has_many :comments
    has_one_attached :video
    has_one_attached :thumbnail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
    end
end

app/controllers/bootstrap_controller.rb
class BootstrapController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  # POST /comments or /comments.json
  def create
    @course = Course.find(params[:course_id])
    @comment = @course.comments.new(comment_params)
    @comment.user = current_user
    

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @course }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:course_id, :body, :user_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show, :upvote, :downvote]
  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = current_admin.courses.build
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = current_admin.courses.build(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Curso criado com sucesso." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Editado com sucesso." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Apagado com sucesso" }
      format.json { head :no_content }
    end
  end

  def upvote
    @course = Course.find(params[:id])
    if admin_signed_in? 
      @course.upvote_by current_admin
      redirect_back fallback_location: root_path
    else
      @course.upvote_by current_user
      redirect_back fallback_location: root_path
    end
  end

  def downvote
    @course = Course.find(params[:id])
    if admin_signed_in? 
      @course.downvote_by current_admin
      redirect_back fallback_location: root_path
    else
      @course.downvote_by current_user
      redirect_back fallback_location: root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :module, :video, :thumbnail)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/bootstrap/index.html.erb
<h1>Bootstrap#index</h1>
<p>Find me in app/views/bootstrap/index.html.erb</p>
<div class="spinner-border text-primary" role="status">
  <span class="sr-only">Loading...</span>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<br>
<div class="alert alert-dismissible alert-light">
    <%= div_for(comment) do %>
        <div class="comments_wrapper clearfix">
            <div class="pull-left">
                <p class="lead"><%= comment.body %></p>
                <% if current_user.avatar.attached? %>
                    <p><%= image_tag current_user.avatar.variant(resize: "20x20!")%><small> <strong> <%= comment.user.name %></strong> a <%= time_ago_in_words(comment.created_at) %> de agora</small></p>
                <% else %>
                    <p><small> <strong> <%= comment.user.name %></strong> a <%= time_ago_in_words(comment.created_at) %> de agora</small></p>
                <% end %>
            </div>
            <div class="btn-group pull-right">
                <% if comment.user == current_user %>
                    <%= link_to 'Deletar', comment, method: :delete, data: { confirm: 'Deseja apagar o comentario?' }, class: "btn btn-danger" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.course_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @comment.course_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/courses/_form.html.erb
  <%= form_with(model: course, local: true) do |form| %>
    <% if course.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>
        <ul>
          <% course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :thumbnail, "Thumbnail" %>
      <%= form.file_field :thumbnail, required: true, class: "form-control"  %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :video, "Video" %>
      <%= form.file_field :video, required: true, class: "form-control"  %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :title, "Titulo" %>
      <%= form.text_field :title, required: true, class: "form-control"  %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :description, "Descrição" %>
      <%= form.text_area :description, required: true, class: "form-control"  %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :module, "Modulo" %>
      <%= form.text_field :module, required: true, class: "form-control"  %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit 'Salvar', class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>

app/views/courses/edit.html.erb
<div class="alert alert-dismissible alert-light">
    <h1>Editar Curso</h1>
    <%= render 'form', course: @course %>
    <br>
    <%= link_to 'Voltar ', @course, class: 'btn btn-warning' %> 
</div>

app/views/courses/index.html.erb
<% @courses.each do |course| %>
  <br>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title"><%= link_to course.title, course %></h4>
      <p><%= image_tag(course.thumbnail, :width=>300) %></p>
      <h6 class="card-subtitle mb-2 text-muted"> <%= course.module %></h6>
      <p>
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Description
              </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <p class="card-text"><%= course.description %></p>
              </div>
            </div>
          </div>
        </div>
      </p>
      
        <div class="btn-group">
          <%= button_to like_course_path(course), method: :put do %>
            Like
            <%= course.get_upvotes.size %>
          <% end %>
          <%= button_to dislike_course_path(course), method: :put do %>
            Dislike
            <%= course.get_downvotes.size %>
          <% end %>
        </div>
    </div>
  </div>
<% end %>

 
<section class="light">
  <div class="container py-2">
    <div class="h1 text-center text-dark" id="pageHeaderTitle">Material do curso</div>
    <% @courses.each do |course| %>
      <article class="postcard light blue">
        <a class="postcard__img_link" href="">
          <%= image_tag(url_for(course.thumbnail), class: "postcard__img", alt:  "Image Title") %>
        </a>
        <div class="postcard__text t-dark">
          <h1 class="postcard__title blue"> <%= link_to course.title, course %></h1>
          <div class="postcard__subtitle small">
            <time datetime="2020-05-25 12:00:00">
              <i class="fas fa-calendar-alt mr-2"></i><%= course.module %>
            </time>
          </div>
          <div class="postcard__bar"></div>
          <div class="postcard__preview-txt"><%= course.description %></div>

          <ul class="postcard__tagbox">
            <li class="tag__item"><i class="fas fa-clock mr-2"></i>55 mins.</li>
            <li class="tag__item play blue">
              <a href="#"><i class="fas fa-play mr-2"></i>Play Episode</a>
            </li>
          </ul>
        </div>
      </article>
    <% end %>
  </div>
</section>

app/views/courses/new.html.erb
<div class="alert alert-dismissible alert-light">
    <h1>Criar curso</h1>
    <%= render 'form', course: @course %>
</div>

app/views/courses/show.html.erb
<div class="page-header">
  <div class="alert alert-dismissible alert-secondary">
    <h1>
      <h2><%= @course.title %></h2><br>
    </h1>
    <p>
      <%= video_tag(url_for(@course.video), :width=>800, controls: '') %>
    </p>
    <p>
      <strong>Module:</strong>
      <%= @course.module %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @course.description %>
    </p>
    <div class="btn-group pull-right">
      <%= link_to like_course_path(@course), method: :put, class: "btn btn-info btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Like
        <%= @course.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_course_path(@course), method: :put, class: "btn btn-ligh btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        Dislike
        <%= @course.get_downvotes.size %>
      <% end %>
    </div>
  </div>
</div>
<% if @course.admin == current_admin %>
  <div class="alert alert-dismissible alert-success">
  <div class="btn-group">
    <%= link_to 'Editar', edit_course_path(@course), class: "btn btn-info" %>
    <%= link_to 'Deletar', @course, method: :delete, data: { confirm: 'Deseja deletar esse item?' }, class: "btn btn-danger" %>
  </div>
  </div>
  <br>
<% end %>
<br>
<div class="alert alert-dismissible alert-secondary">
  <h4 class="comments_title">
  <%= @course.comments.count %> Comentarios
  </h4>
  <% if user_signed_in? %>
    <%= simple_form_for [@course, Comment.new] do |f| %>
      <div class="field">
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Comentar", class: "btn btn-primary" %>
    <% end %>
  <% end %>
  <div id="comments">
    <%= render :partial => @course.comments %>
  </div>
</div>

app/views/home/index.html.erb
<br>
<% if admin_signed_in? %>
    <div class="alert alert-dismissible alert-light">
        <% if current_admin.avatar.attached? %>
            <%= image_tag current_admin.avatar.variant(resize: "50x50!") %>
        <% end %>
        <h1><%= current_admin.name %></h1>
        <figure>
            <blockquote class="blockquote">
                <p class="mb-0">Bem vindo a plataforma de cursos da Unilexia</p>
            </blockquote>
        </figure>
    </div> 
<% elsif user_signed_in? %>
    <div class="alert alert-dismissible alert-light">
        <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.variant(resize: "50x50!") %>
        <% end %>
        <h1><%= current_user.name %></h1>
        <figure>
            <blockquote class="blockquote">
                <p class="mb-0">Bem vindo a plataforma de cursos da Unilexia</p>
            </blockquote>
        </figure>       
    </div>            
<% else %>
    <div class="alert alert-dismissible alert-light">
        <h1>Bem vindo a plataforma de cursos da Unilexia</h1>
        <figure>
            <blockquote class="blockquote">
                <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            </blockquote>
            <figcaption class="blockquote-footer">
                Someone famous in <cite title="Source Title">Source Title</cite>
            </figcaption>
        </figure>
    </div> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discovery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body style="background-image: url(<%= image_path("wall.jpg")%>); background-size: 100%;">
    
    <% if admin_signed_in? %>
      <%= render 'shared/navbarAdmin'%>
    <% elsif user_signed_in? %>
      <%= render 'shared/navbarUser'%>
    <% else %>
      <%= render 'shared/navbarHome'%>
    <% end %>
    

    <div id="main_content" class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
        <div id="content" class="col-md-9 center-block">
          <%= yield %>
        </div>
    </div>
   
  </body>
</html>

app/views/shared/_footer.html.erb
<br>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
<footer class="footer bg-footer footer-bar">
    <div class="container text-center">
        <div class="row align-items-center">
            <div class="col-sm-6">
                <div class="text-sm-left">
                    <p class="mb-0">&copy; 2020. Design with <i class="mdi mdi-heart text-danger"></i></p>
                </div>
            </div><!--end col-->

            <div class="col-sm-6 mt-4 mt-sm-0 pt-2 pt-sm-0">
                <ul class="list-unstyled text-sm-right social-icon social mb-0">
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i class="mdi mdi-facebook" title="Facebook"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i class="mdi mdi-instagram" title="Instagram"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i class="mdi mdi-twitter" title="Twitter"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i class="mdi mdi-google-plus" title="Google +"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i class="mdi mdi-linkedin" title="Linkedin"></i></a></li>
                </ul><!--end icon-->
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</footer>

app/views/shared/_navbarAdmin.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Administrador", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <% if admin_signed_in? %>
            <li class="nav-item"><%= link_to 'Adicionar Curso/Modulo', new_course_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Curso', courses_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Conta', edit_admin_registration_path, class: "nav-link" %></li>
            
        <% else %>
            
        <% end %>
      </ul>
      <form class="d-flex">
        <%= link_to 'Sair', destroy_admin_session_path, :method => :delete, class: "btn btn-danger my-2 my-sm-0" %>
      </form>
    </div>
  </div>
</nav>
<br>

app/views/shared/_navbarHome.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Unilexia", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
      </ul>
      <form class="d-flex">
        <%= link_to 'Login', user_session_path, class: "btn btn-light action-button my-2 my-sm-0" %>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_navbarUser.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Usuario", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
         <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Conta', edit_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Curso', courses_path, class: "nav-link" %></li>
        <% else %>
            
        <% end %>
      </ul>
      <form class="d-flex">
        <%= link_to 'Sair', destroy_user_session_path, :method => :delete, class: "btn btn-danger my-2 my-sm-0" %>
      </form>
    </div>
  </div>
</nav>
<br>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>